
CREATE TABLE EMPLOYEE (
  empId INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  dept TEXT NOT NULL
);

 
INSERT INTO EMPLOYEE VALUES (0001, 'Clark', 'Sales');
INSERT INTO EMPLOYEE VALUES (0002, 'Dave', 'Accounting');
INSERT INTO EMPLOYEE VALUES (0003, 'Ava', 'Sales');

BEGIN;

DECLARE my_cursor CURSOR FOR SELECT name, dept FROM EMPLOYEE WHERE name IS NOT NULL;

FETCH FROM my_cursor;

CLOSE my_cursor;

COMMIT;

